version: "3.3"
services:
  webserver:
    build: 
      context: ./app_react
      dockerfile: Dockerfile.prd
      args:
        - APP_HOST=$APP_HOST
        - APP_HOST_API=$APP_HOST_API
        - APP_BACKEND_PORT=$APP_BACKEND_PORT
        - NGINX_CONF_TEMPLATE=$NGINX_CONF_TEMPLATE
    ports:
      - 80:80
      - 443:443
      - ${APP_BACKEND_PORT}:8080
    volumes: 
      - ./certbot_webroot/:/var/www/certbot_webroot
      - /etc/letsencrypt:/etc/letsencrypt
  nodeapp:
    build:
      context: ./app_node
      dockerfile: Dockerfile.prd
    environment:
      - APP_CROSS_ORIGIN_ALLOW=http://$APP_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - pg_data:/var/lib/postgresql
      - ./sql/structure.sql:/docker-entrypoint-initdb.d/1-structure.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
      - $POSTGRES_PORT:5432
volumes:
  pg_data: