version: "3.3"
services:
    webserver:
        build: 
            context: ./app_react
            args:
                - APP_HOST_URL=$APP_HOST_URL
                - APP_BACKEND_PORT=$APP_BACKEND_PORT
        ports:
            - 80:80
            - ${APP_BACKEND_PORT}:8080
    nodeapp:
        build: ./app_node
        environment:
            - APP_HOST_URL=$APP_HOST_URL
    db:
        image: postgres:14
    nginx:
        image: nginx:1.21.3