version: "3.3"
services:
    webserver:
        build: 
            context: ./app_react
            args:
                - REACT_APP_NODE_URL=$APP_NODE_URL
                - REACT_APP_REACT_URL=$APP_REACT_URL
        ports:
            - 80:80
            - 8080:8080
    nodeapp:
        build: ./app_node
        environment:
            - APP_REACT_URL=$APP_REACT_URL
    db:
        image: postgres:14
    nginx:
        image: nginx:1.21.3