version: "3.3"
services:
  reactapp:
    build: 
      context: ./app_react
      dockerfile: Dockerfile.dev
      args:
        - APP_HOST_URL=$APP_HOST_URL
        - APP_BACKEND_PORT=$APP_BACKEND_PORT
    ports:
      - 80:3000
    volumes:
      - ./app_react:/app/
      - ./app_react/node_modules:/app/node_modules/
  nodeapp:
    build:
      context: ./app_node
      dockerfile: Dockerfile.dev
    environment:
      - APP_FRONTEND_URL=$APP_HOST_URL
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
    ports:
      - ${APP_BACKEND_PORT}:3000
    volumes:
      - ./app_node:/app/
      - ./app_node/node_modules:/app/node_modules/
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - pg_data:/var/lib/postgresql
      - ./sql/structure.sql:/docker-entrypoint-initdb.d/1-structure.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
      - $POSTGRES_PORT:5432
volumes:
  pg_data: